client_id = "b0c8fde9d4a46a7afca1e8c460c8e005"
application_url = "https://premium-transaction-app.vercel.app"
embedded = true
name = "premium-transaction-app"

[access_scopes]
scopes = "write_draft_orders,read_products,read_customers,read_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://premium-transaction-app.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
